# Generated by Django 5.1 on 2024-08-08 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='должность')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='подразделение')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.department', verbose_name='подразделение')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='фамилия')),
                ('father_name', models.CharField(blank=True, max_length=50, verbose_name='отчество')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='размер заработной платы')),
                ('date_joined', models.DateField(blank=True, null=True, verbose_name='дата приема на работу')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.department', verbose_name='подразделение')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.position', verbose_name='должность')),
            ],
        ),
    ]
