# Generated by Django 5.1 on 2024-08-08 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_department_options_alter_position_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='position',
            field=models.CharField(db_index=True, max_length=255, verbose_name='должность'),
        ),
        migrations.AlterField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.department', verbose_name='подразделение'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workers', to='main.department', verbose_name='подразделение'),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
